# Generated by Django 4.2.20 on 2025-05-15 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                ("location_id", models.AutoField(primary_key=True, serialize=False)),
                ("region_name", models.CharField(max_length=50)),
                ("specific_name", models.CharField(max_length=100)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=10)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="Picture",
            fields=[
                ("picture_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "s3_key",
                    models.CharField(
                        blank=True,
                        help_text="S3 버킷 내의 파일 경로 (예: temp/filename.jpg 또는 saved/2023/01/filename.jpg)",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("temp", "임시 저장"), ("saved", "저장 완료")],
                        default="temp",
                        help_text="이미지 상태 (임시 저장/저장 완료)",
                        max_length=10,
                    ),
                ),
                (
                    "picture_caption",
                    models.TextField(blank=True, help_text="이미지 캡션", null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pictures",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PictureKeyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link_type",
                    models.CharField(
                        choices=[
                            ("from_picture", "From Picture"),
                            ("from_keyword", "From Keyword"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "keyword",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="events.keyword"
                    ),
                ),
                (
                    "picture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="galleries.picture",
                    ),
                ),
            ],
            options={
                "unique_together": {("picture", "keyword")},
            },
        ),
    ]
