# Generated by Django 4.2.20 on 2025-05-15 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("event_id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.CharField(blank=True, max_length=50, null=True)),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                ("time", models.CharField(blank=True, max_length=50, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("event_emotion_id", models.IntegerField(default=1)),
                ("weather", models.CharField(default="sunny", max_length=50)),
                ("memo_content", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "이벤트",
                "verbose_name_plural": "이벤트 목록",
            },
        ),
        migrations.CreateModel(
            name="Keyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=50)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keywords",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "verbose_name": "이벤트 키워드",
                "verbose_name_plural": "이벤트 키워드 목록",
            },
        ),
        migrations.CreateModel(
            name="Timeline",
            fields=[
                ("timeline_id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                ("event_ids_series", models.TextField(blank=True, null=True)),
                (
                    "events",
                    models.ManyToManyField(related_name="timelines", to="events.event"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("date", "user")},
            },
        ),
    ]
