# Generated by Django 4.2.20 on 2025-05-18 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="tag",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="keyword",
            unique_together={("event", "content")},
        ),
    ]
