# Generated by Django 4.2.20 on 2025-05-15 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("diaries", "0002_initial_emotions"),
    ]

    operations = [
        migrations.AddField(
            model_name="diary",
            name="emotion_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="diaries.emotion",
            ),
        ),
    ]
